update utils pkg
projectdiscovery/httpx pull request #1100
Opened 2023-04-17 18:16 UTC by RamanaReddy0M

2023-04-17 18:19 UTC, RamanaReddy0M commented
upstream pr: https://github.com/projectdiscovery/utils/pull/133

2023-04-18 06:01 UTC, RamanaReddy0M commented
```console
 ./httpx -u http.s3.amazonaws.com -v       

    __    __  __       _  __
   / /_  / /_/ /_____ | |/ /
  / __ \/ __/ __/ __ \|   /
 / / / / /_/ /_/ /_/ /   |
/_/ /_/\__/\__/ .___/_/|_|
             /_/

                projectdiscovery.io

https://http.s3.amazonaws.com
```

2023-04-18 13:08 UTC, Mzack9999 requested changes
Please bump to `https://github.com/projectdiscovery/utils@v0.0.21` (Just released)

2023-04-18 13:29 UTC, Mzack9999 approved these changes

2023-04-18 13:38 UTC, ehsandeep approved these changes

2023-04-18 13:38 UTC, merged