remove fullurl from req-res
projectdiscovery/httpx pull request #1337
Opened 2023-08-31 09:33 UTC by dogancanbakir

This PR removes fullURL storage when using `-store-response`.  Possible solution to #1317.

before:
```console
$ cat pastebin.com/resp.txt
https://pastebin.com/raw/TYsVwM0n

GET /raw/TYsVwM0n HTTP/1.1
Host: pastebin.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; rv:9.0) Gecko/20100101 Firefox/9.0
Accept-Charset: utf-8
Accept-Encoding: gzip

HTTP/1.1 200 OK
Connection: close
Transfer-Encoding: chunked
Age: 45
Cache-Control: public, max-age=1801
Cf-Cache-Status: HIT
Cf-Ray: 7ff435236ac3286e-OTP
Content-Type: text/plain; charset=utf-8
Date: Thu, 31 Aug 2023 09:22:11 GMT
Last-Modified: Thu, 31 Aug 2023 09:21:26 GMT
Server: cloudflare
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Xss-Protection: 1;mode=block

38
line1
this is a line containing HTTP/1.1 FOO BAR
line3
0

$ cat main.go
package main

import (
	"bufio"
	"bytes"
	"fmt"
	"net/http"
	"os"
)

func main() {
	data, _ := os.ReadFile("test.txt")
	br := bufio.NewReader(bytes.NewReader(data))
	req, err := http.ReadRequest(br)
	fmt.Println(err, req)
	fmt.Println()
	res, err := http.ReadResponse(br, req)
	fmt.Println(err, res)
}

$ go run .
malformed HTTP request "https://pastebin.com/raw/TYsVwM0n" <nil>

malformed HTTP response "" <nil>
```

after:
```console
$ cat pastebin.com/resp.txt
GET /raw/TYsVwM0n HTTP/1.1
Host: pastebin.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; rv:9.0) Gecko/20100101 Firefox/9.0
Accept-Charset: utf-8
Accept-Encoding: gzip

HTTP/1.1 200 OK
Connection: close
Transfer-Encoding: chunked
Age: 45
Cache-Control: public, max-age=1801
Cf-Cache-Status: HIT
Cf-Ray: 7ff435236ac3286e-OTP
Content-Type: text/plain; charset=utf-8
Date: Thu, 31 Aug 2023 09:22:11 GMT
Last-Modified: Thu, 31 Aug 2023 09:21:26 GMT
Server: cloudflare
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Xss-Protection: 1;mode=block

38
line1
this is a line containing HTTP/1.1 FOO BAR
line3
0

$ cat main.go
package main

import (
	"bufio"
	"bytes"
	"fmt"
	"net/http"
	"os"
)

func main() {
	data, _ := os.ReadFile("test.txt")
	br := bufio.NewReader(bytes.NewReader(data))
	req, err := http.ReadRequest(br)
	fmt.Println(err, req)
	fmt.Println()
	res, err := http.ReadResponse(br, req)
	fmt.Println(err, res)
}

$ go run .
<nil> &{GET /raw/TYsVwM0n HTTP/1.1 1 1 map[Accept-Charset:[utf-8] Accept-Encoding:[gzip] User-Agent:[Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; rv:9.0) Gecko/20100101 Firefox/9.0]] {} <nil> 0 [] false pastebin.com map[] map[] <nil> map[]  /raw/TYsVwM0n <nil> <nil> <nil> <nil>}

<nil> &{200 OK 200 HTTP/1.1 1 1 map[Age:[45] Cache-Control:[public, max-age=1801] Cf-Cache-Status:[HIT] Cf-Ray:[7ff435236ac3286e-OTP] Content-Type:[text/plain; charset=utf-8] Date:[Thu, 31 Aug 2023 09:22:11 GMT] Last-Modified:[Thu, 31 Aug 2023 09:21:26 GMT] Server:[cloudflare] Vary:[Accept-Encoding] X-Content-Type-Options:[nosniff] X-Frame-Options:[DENY] X-Xss-Protection:[1;mode=block]] 0x400006a240 -1 [chunked] true false map[] 0x400012a000 <nil>}
```

2023-09-04 08:31 UTC, tarunKoyalwar approved these changes
lgtm !

```console
$ ./httpx -u projectdiscovery.io -screenshot && nuclei -u output/response/projectdiscovery.io -passive

    __    __  __       _  __
   / /_  / /_/ /_____ | |/ /
  / __ \/ __/ __/ __ \|   /
 / / / / /_/ /_/ /_/ /   |
/_/ /_/\__/\__/ .___/_/|_|
             /_/

		projectdiscovery.io

[INF] Current httpx version v1.3.4 (latest)
https://projectdiscovery.io

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.13

		projectdiscovery.io

[INF] Current nuclei version: v2.9.13 (latest)
[INF] Current nuclei-templates version: v9.6.2 (latest)
[INF] New templates added in latest release: 61
[INF] Templates loaded for current scan: 881
[INF] Targets loaded for current scan: 1
[metatag-cms] [] [info] output/response/projectdiscovery.io/8dc78052bc714ad90b93ebabae752a988f4807e4.txt [Framer 7aa0232]
[tech-detect:cloudflare] [] [info] output/response/projectdiscovery.io/8dc78052bc714ad90b93ebabae752a988f4807e4.txt
```

2023-09-05 09:50 UTC, Mzack9999 requested changes
This was an explicit choice to be consistent with https://github.com/tomnomnom/meg indexing. Indeed it's would break every RFC compliant request/response reader. What do you think if we put the full url at the very bottom of the file like this:

```
[request]

[response]
\n
\n
[full url]
```

In this way it should be ignored by parser as it should end processing the body respecting the content-header or transfer encoding start/end markers.

2023-09-06 17:03 UTC, Mzack9999 approved these changes

2023-09-06 17:54 UTC, ehsandeep approved these changes

2023-09-06 17:54 UTC, merged