Introducing CanHaveTitleTag Function for MIME Type Validation
projectdiscovery/httpx pull request #1608
Opened 2024-03-02 23:36 UTC by RedYetiDev

This pull request introduces a new function called `CanHaveTitleTag`. The purpose of this function is to validate whether a given MIME type supports the extraction of a `<title>` tag from its content. The motivation behind this addition is to address issues where the extractor incorrectly assumes support for a `<title>` tag, even when it's not applicable, such as in `application/json` MIME types.

**Changes:**

1. Added a new function `CanHaveTitleTag` in `title.go` to perform validation for MIME types supporting `<title>` tag extraction.
2. Updated `runner.go` to use the new function

> [!NOTE]
> I'm not a frequent **go** developer, and this may be an ineffective way to achieve this goal, but from what I can tell, it gets the job done.

2024-03-07 12:26 UTC, RedYetiDev commented
Hi! I noticed that some of the builds were failing with `use of untyped nil in assignment`, does that have to do with `title := nil`? How do I fix that?

2024-03-07 13:34 UTC, dogancanbakir requested changes
I left some comments for you; thanks for the PR!

2024-03-07 13:34 UTC, dogancanbakir commented on common/httpx/title.go
> +    mimeTypes := []string{
Let's move mime types to the beginning of this file as
```go
var (
	cutset                  = "\n\t\v\f\r"
	reTitle                 = regexp.MustCompile(`(?im)<\s*title.*>(.*?)<\s*/\s*title>`)
	reContentType           = regexp.MustCompile(`(?im)\s*charset="(.*?)"|charset=(.*?)"\s*`)
	supportedTitleMimeTypes = []string{
		"text/html",
		"application/xhtml+xml",
		"application/xml",
		"application/rss+xml",
		"application/atom+xml",
		"application/xhtml+xml",
		"application/vnd.wap.xhtml+xml",
	}
)
```
and refactor this function as

```go
func CanHaveTitleTag(mimeType string) bool {
	return slices.Contains(supportedTitleMimeTypes, mimeType)
}
```

2024-03-07 13:34 UTC, dogancanbakir commented on runner/runner.go
> +	title := nil
Let's change this section as

```go
var title string
	if httpx.CanHaveTitleTag(resp.GetHeaderPart("Content-Type", ";")) {
		title = httpx.ExtractTitle(resp)
	}

	if scanopts.OutputTitle && title != "" {
		builder.WriteString(" [")
		if !scanopts.OutputWithNoColor {
			builder.WriteString(aurora.Cyan(title).String())
		} else {
			builder.WriteString(title)
		}
		builder.WriteRune(']')
	}
```

2024-03-07 14:51 UTC, dogancanbakir requested changes

2024-03-07 14:51 UTC, dogancanbakir commented on common/httpx/title.go
> +    return slices.Contains(supportedTitleMimeTypes, mimeType)
import `"slices"`

2024-03-07 14:55 UTC, RedYetiDev commented on common/httpx/title.go
> +    return slices.Contains(supportedTitleMimeTypes, mimeType)
Right! Sorry!

2024-03-07 14:58 UTC, RedYetiDev commented
I think I undid the dev changes in my push, once this is ready, I'll squash and open a new pull if you'd like.

2024-03-07 15:46 UTC, dogancanbakir approved these changes

2024-03-07 19:16 UTC, RedYetiDev commented
The latest commit shouldn't cause any issues, I updated the patch to match the code on the dev branch rather than the main branch.

2024-03-12 00:43 UTC, RedYetiDev commented
Hi, seeing as there are 11 commits for this, I feel like squashing might be wise, is that done during the merge process, or should I do it and re-open a pull?

2024-03-20 17:04 UTC, RedYetiDev commented
Hi, any update on this?

2024-03-21 12:18 UTC, Mzack9999 approved these changes

2024-03-23 16:17 UTC, ehsandeep approved these changes

2024-03-23 16:17 UTC, merged

2024-03-23 16:33 UTC, RedYetiDev commented
Thanks!