fix missing favicon hash for targets
projectdiscovery/httpx pull request #1848
Opened 2024-07-31 08:44 UTC by RamanaReddy0M

2024-07-31 08:55 UTC, RamanaReddy0M commented
```console
✗ ./httpx -u "https://0-cenka.ru,https://0360.ru,https://www.viber.com,https://favicon.io/emoji-favicons/alien/,https://00j.ru/" -favicon -fr -fhr

    __    __  __       _  __
   / /_  / /_/ /_____ | |/ /
  / __ \/ __/ __/ __ \|   /
 / / / / /_/ /_/ /_/ /   |
/_/ /_/\__/\__/ .___/_/|_|
             /_/

                projectdiscovery.io

[INF] Current httpx version v1.6.6 (latest)
[WRN] UI Dashboard is disabled, Use -dashboard option to enable
https://www.viber.com [https://www.viber.com/en/] [1550133834]
https://favicon.io/emoji-favicons/alien/ [1352067985]
https://00j.ru/ [1871456111]
https://0360.ru [-1805840784]
https://0-cenka.ru [-1211857331]
```

2024-08-05 18:33 UTC, dwisiswant0 requested changes
I'm not really sure if this is a practical step to perform a check using a "data:image/" prefix instead of validating the whole mimetype with a `^data:(image\/.+);base64,` pattern. Or maybe, we could use `mime.ParseMediaType` to dodge issues with invalid chars/padding and to future-proof our code against possible MIME type variants.

2024-08-05 18:33 UTC, dwisiswant0 commented on runner/runner.go
> +		isFavUrl, isBas64FavIcon := err == nil, false
```suggestion
		isFavURL, isBase64FavIcon := err == nil, false
```

To maintain consistency and fix a typo.

2024-08-05 18:33 UTC, dwisiswant0 commented on common/stringz/stringz.go
> +func IsBase64Icon(iconBase64 string) bool {
Low-level thing; early return for empty string.

2024-08-05 18:33 UTC, dwisiswant0 commented on common/stringz/stringz.go
> +func DecodeBase64Icon(iconBase64 string) ([]byte, error) {
Low-level thing; early return for empty string.

2024-08-07 11:11 UTC, dwisiswant0 approved these changes

2024-08-09 18:54 UTC, ehsandeep approved these changes

2024-08-09 18:54 UTC, merged