Exclude response, request data from result
projectdiscovery/httpx pull request #1944
Opened 2024-10-11 09:17 UTC by dogancanbakir

Closes #1914

2024-11-06 17:41 UTC, Mzack9999 requested changes
What do you think about using something like `github.com/jszwec/csvutil` with `csv:"body,omitempty"`?

2024-11-07 10:07 UTC, dogancanbakir commented
Let's create a follow-up issue to assess this option, as it may involve replacing CSV-related mappings with this package.

2024-11-08 14:57 UTC, Mzack9999 approved these changes
Follow up ticket at https://github.com/projectdiscovery/httpx/issues/1984 - This PR excludes the fields in export, potentially creating missing data if expected

2025-01-27 10:20 UTC, ehsandeep approved these changes

2025-01-27 10:20 UTC, merged