Remove * and/or . (prefix) from target
projectdiscovery/httpx pull request #452
Opened 2021-12-06 12:23 UTC by parrasajad

to fix #447

2021-12-06 16:01 UTC, ehsandeep requested changes
duplicate input check in missing like httpx does in other cases.

```
$echo in.search.yahoo.com | ./httpx -silent -tls-probe | wc -l
78

$echo in.search.yahoo.com | ./httpx -silent -tls-probe | sort -u | wc -l
62
```

2021-12-06 20:25 UTC, Mzack9999 commented
We can reuse the helper function added to stream modality to avoid dupes: https://github.com/projectdiscovery/httpx/blob/d7e081c08a1e16a79c20f40a1b20e21f2c10d151/runner/runner.go#L320 can be used

2021-12-07 11:26 UTC, Mzack9999 approved these changes

2021-12-08 15:07 UTC, ehsandeep approved these changes

2021-12-08 15:07 UTC, merged