Expose CDN Name in output and json
projectdiscovery/httpx pull request #499
Opened 2022-01-15 00:21 UTC by Ice3man543

2022-01-16 09:18 UTC, ehsandeep requested changes
```console
echo https://www.hackerone.com | ./httpx -silent -cdn

https://www.hackerone.com [projectdiscovery]
```

2022-01-19 20:40 UTC, brenocss commented
The cdn field shouldn't be omitted when false. https://github.com/projectdiscovery/httpx/issues/496
```json
"cdn": false
```

2022-02-07 11:47 UTC, ehsandeep approved these changes

2022-02-07 13:25 UTC, Mzack9999 approved these changes

2022-02-07 13:48 UTC, merged