hash improvement
projectdiscovery/httpx pull request #528
Opened 2022-02-25 18:11 UTC by LuitelSamikshya

2022-02-25 20:08 UTC, ehsandeep requested changes
There is slight change on mmh3 hash genration with `favicon` flag vs the default one, the default one can be adoped to mimic the pythoic (`-favicon`) mmh3 hash.

```console
echo https://mta-sts.forwarding.hackerone.com/favicon.ico | ./httpx -hash mmh3 -silent
https://mta-sts.forwarding.hackerone.com/favicon.ico [2594644036]

echo https://mta-sts.forwarding.hackerone.com | ./httpx -favicon -silent
https://mta-sts.forwarding.hackerone.com/favicon.ico [-1700323260]
```

2022-02-25 20:17 UTC, ehsandeep requested changes
As it's unclear the types of hashes are supported, this information can be made available to help menu by printing `hashType`

```
-hash string         Display response body hash (supported: md5,mmh3,sha256,sim)
```

2022-02-26 09:58 UTC, M09Ic commented
> ```
> https://mta-sts.forwarding.hackerone.com/favicon.ico
> ```

This bug is because I forgot to convert the final mmh3 hash to int32.
 
just change:
`common/hashes/Mmh3` 
```
func Mmh3(data []byte) string {
	var h32 = murmur3.New32WithSeed(0)
	h32.Write(stdBase64(data))
	return fmt.Sprintf("%d", int32(h32.Sum32()))
}
```

test:
`echo "https://www.bilibili.com/" | httpx -favicon -hash mmh3`

`https://www.bilibili.com/favicon.ico [-1825654886] [-1825654886]`

2022-02-28 18:23 UTC, ehsandeep approved these changes

2022-03-01 05:20 UTC, Mzack9999 approved these changes

2022-03-01 06:35 UTC, merged