added ascii hostname support
projectdiscovery/httpx pull request #615
Opened 2022-05-12 19:51 UTC by LuitelSamikshya

2022-05-13 07:20 UTC, Mzack9999 requested changes

2022-05-13 07:20 UTC, Mzack9999 commented on go.sum
> +github.com/projectdiscovery/fastdialer v0.0.16-0.20220512171112-e6cca11bc933 h1:0roPUQaDmZOXe2Ua15jzGMVMCH8Cd32us9LcF73H+xs=
Depends on https://github.com/projectdiscovery/fastdialer/pull/36#discussion_r872074415

2022-05-13 20:47 UTC, LuitelSamikshya commented on go.sum
> +github.com/projectdiscovery/fastdialer v0.0.16-0.20220512171112-e6cca11bc933 h1:0roPUQaDmZOXe2Ua15jzGMVMCH8Cd32us9LcF73H+xs=
Done

2022-05-15 10:59 UTC, Mzack9999 approved these changes

2022-05-15 11:00 UTC, merged

2022-05-15 18:07 UTC, ehsandeep commented
follow up ticket - https://github.com/projectdiscovery/httpx/issues/619