Issue 735+issue 739
projectdiscovery/httpx pull request #757
Opened 2022-09-07 23:14 UTC by LuitelSamikshya

2022-09-08 08:36 UTC, ehsandeep requested changes
- [x] Validation error even when `silent` flag is not used.

```console
echo google.com | ./httpx -v

    __    __  __       _  __
   / /_  / /_/ /_____ | |/ /
  / __ \/ __/ __/ __ \|   /
 / / / / /_/ /_/ /_/ /   |
/_/ /_/\__/\__/ .___/_/|_|
             /_/              v1.2.4

		projectdiscovery.io

Use with caution. You are responsible for your actions.
Developers assume no liability and are not responsible for any misuse or damage.
[FTL] verbose flag is incompatible with silent flag
```

- [x] Missing test for multiple header input bug

2022-09-08 10:30 UTC, Mzack9999 requested changes
The tool is erroring even when `-silent` is not used:
```console
$ echo https://192.168.1.1 | go run . -debug
...
[FTL] debug flag is incompatible with silent flag
exit status 1
```

2022-09-12 23:06 UTC, ehsandeep approved these changes
```console
echo google.com | ./httpx -silent -v
[FTL] verbose flag is incompatible with silent flag
```

```console
echo google.com | ./httpx -H 'foo: bar' -H 'user-agent: curl/7.79.1' -debug-req

    __    __  __       _  __
   / /_  / /_/ /_____ | |/ /
  / __ \/ __/ __/ __ \|   /
 / / / / /_/ /_/ /_/ /   |
/_/ /_/\__/\__/ .___/_/|_|
             /_/              v1.2.4

		projectdiscovery.io

Use with caution. You are responsible for your actions.
Developers assume no liability and are not responsible for any misuse or damage.
[INF] Dumped HTTP request for https://google.com:443

GET / HTTP/1.1
Host: google.com
User-Agent: curl/7.79.1
Accept-Charset: utf-8
Foo: bar
Accept-Encoding: gzip
```

2022-09-13 11:14 UTC, Ice3man543 approved these changes

2022-09-13 11:16 UTC, merged