Added flag for single or comma separated stdin input values (#737)
projectdiscovery/httpx pull request #759
Opened 2022-09-09 18:29 UTC by ariasmn

There are a couple of things which I don't know if are ok:
- Variable/function naming. Non-native speaker so maybe the spelling is wrong.
- You can input from the stdin and a file (using both the **_-l_** and _**-u**_ flags) at the same time.
- Did not add any tests because I didn't fully understand how these works. I can do some if needed with some guidance.

2022-09-20 06:38 UTC, ariasmn commented
Hey, just wanted to check the current status of the PR and ask if there is anything more I could do to help

2022-09-20 14:12 UTC, forgedhallpass commented on runner/runner.go
> +	if r.options.InputTargetHost != "" {
We should use the logic from `goflags` that automatically splits the input into a slice. See `StringSliceVarP`

2022-09-20 14:13 UTC, forgedhallpass commented on runner/runner.go
> +	if r.options.InputTargetHost != "" {
You could check how it has been done in other projects of ours (e.g. `nuclei` or `dnsx`)

2022-09-20 14:14 UTC, forgedhallpass requested changes
Please see my comments.

2022-09-20 17:51 UTC, ariasmn commented
Done! Just updated the PR.

Please let me know if everything is ok.

2022-09-21 13:19 UTC, Ice3man543 approved these changes
lgtm

2022-09-21 13:23 UTC, forgedhallpass approved these changes

2022-09-21 14:33 UTC, ehsandeep approved these changes
```console
./httpx -u example.com,google.com -silent

https://google.com
https://example.com
```

2022-09-21 14:33 UTC, merged