add stored_response_path to output json
projectdiscovery/httpx pull request #832
Opened 2022-10-25 07:12 UTC by parrasajad

Example:
```console
echo https://example.com/ | httpx -json --srd /tmp/httpx.tmp | jq   

    __    __  __       _  __
   / /_  / /_/ /_____ | |/ /
  / __ \/ __/ __/ __ \|   /
 / / / / /_/ /_/ /_/ /   |
/_/ /_/\__/\__/ .___/_/|_|
             /_/              v1.2.4

                projectdiscovery.io

Use with caution. You are responsible for your actions.
Developers assume no liability and are not responsible for any misuse or damage.
```
```json
{
  "timestamp": "2022-10-25T12:34:11.669733+05:30",
  "hash": {
    "body_md5": "84238dfc8092e5d9c0dac8ef93371a07",
    "body_mmh3": "-1139337416",
    "body_sha256": "ea8fac7c65fb589b0d53560f5251f74f9e9b243478dcb6b3ea79b5e36449c8d9",
    "body_simhash": "9899951357530060719",
    "header_md5": "0c71aafac005267cf853306684506e1e",
    "header_mmh3": "2132970353",
    "header_sha256": "8b20d69636bf8cc058c96c64d5c215a4f6898da39faf22cf2c287af7a6c1ca81",
    "header_simhash": "15614706818132709225"
  },
  "port": "443",
  "url": "https://example.com:443",
  "input": "https://example.com/",
  "title": "Example Domain",
  "scheme": "https",
  "webserver": "ECS (dcb/7EEC)",
  "content_type": "text/html",
  "method": "GET",
  "host": "93.184.216.34",
  "path": "/",
  "time": "1.211279375s",
  "a": [
    "93.184.216.34",
    "2606:2800:220:1:248:1893:25c8:1946"
  ],
  "words": 298,
  "lines": 47,
  "status_code": 200,
  "content_length": 1256,
  "failed": false,
  "stored_response_path": "/tmp/httpx.tmp/example.com.txt"
}
```

2022-10-25 15:54 UTC, LuitelSamikshya approved these changes

2022-10-25 19:04 UTC, Mzack9999 requested changes
File system paths must use `filepath` package

2022-10-25 19:04 UTC, Mzack9999 commented on runner/runner.go
> +		responsePath = path.Join(scanopts.StoreResponseDirectory, domainFile)
`path.Join` => `filepath.Join`

2022-10-25 19:04 UTC, Mzack9999 commented on runner/runner.go
> +			responsePath = path.Join(scanopts.StoreResponseDirectory, domainFile)
`path.Join` => `filepath.Join`

2022-10-27 06:36 UTC, Mzack9999 approved these changes

2022-10-27 08:54 UTC, ehsandeep approved these changes

2022-10-27 08:55 UTC, merged