adds base64 encoding support (#813)
projectdiscovery/httpx pull request #885
Opened 2022-11-22 19:30 UTC by tarunKoyalwar

# Description

- Adds base64 encoding to  request and response in json mode.
 
```sh
   -irrb, -include-response-base64   include base64 encoded http request/response in JSON output (-json only)
```
- Below JSON Fields are base64 encoded
  -  request // entire request
  - raw_header // response headers
  - body. // response body

### Run Below Command to Verify

```sh
echo "projectdiscovery.io/xxx" | ./httpx -irrb -json | jq .
```

closes #813

2022-11-23 11:48 UTC, Mzack9999 requested changes
minor changes suggested

2022-11-23 11:48 UTC, Mzack9999 commented on runner/options.go
> +	B64ResponseInStdout       bool
Let's be verbose: `b64` => `base64`

2022-11-23 11:48 UTC, Mzack9999 commented on runner/runner.go
> +func b64(bin []byte) string {
maybe we can move this to `common/stringz/stringz.go`?

2022-11-24 08:13 UTC, Mzack9999 approved these changes
lgtm - Example:
```console
$ echo "projectdiscovery.io/xxx" | go run . -irrb -json -o test.json
$ cat test.json | jq
```

2022-11-24 16:20 UTC, ehsandeep approved these changes

2022-11-24 16:20 UTC, merged