bom utf8 on csv output
projectdiscovery/httpx pull request #887
Opened 2022-11-24 15:04 UTC by xm1k3

2022-11-24 22:02 UTC, Mzack9999 requested changes
- [ ] Remove debug code
- [ ] Excel behaves in the same way with/without sbom => Posted a question on the corresponding issue

2022-11-28 06:38 UTC, Mzack9999 requested changes

2022-11-28 06:38 UTC, Mzack9999 commented on runner/runner.go
> +			if outEncoding == "utf-8" || outEncoding == "utf8" {
`stringsutil.EqualFoldAny(outEncoding, "utf-8", "utf8")`

2022-11-29 06:35 UTC, Mzack9999 approved these changes
```console
$ echo 192.168.1.1 | go run . -o test -csv -csvo utf8
...
timestamp,asn,csp,tls,hash,extract_regex,cdn_name,port,url,input,location,title,scheme,error,webserver,body,content_type,method,host,path,favicon,final_url,header,raw_header,request,time,jarm,chain_status_codes,a,cname,tech,extracts,chain,words,lines,status_code,content_length,failed,vhost,websocket,cdn,http2,pipeline,stored_response_path
...
```

2022-11-29 06:48 UTC, ehsandeep approved these changes

2022-11-29 06:48 UTC, merged